server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jobterview?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    username: root
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:

         show_sql: true
#        format_sql: true


#  security:
#    oauth2:W
#      client:
#        registration:
#          google:
#            client-id: 682444755899-3eqgd34dqavn8mq0us3q4e0lf09pbc4v.apps.googleusercontent.com
#            client-secret: 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
#            scope:
#              - email
#              - profile

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

mail:
  smtp:
    timeout: 5000
    auth: true
    starttls:
      required: true
      enable: true
    socketFactory:
      class: javax.net.ssl.SSLSocketFactory
      fallback: false
      port: 465
    port: 465
    host: smtp.gmail.com

AdminMail:
  id: jobterview1@gmail.com
  password: sfktdjrnyxckwdka