#사용할 변수
varialbles:
# 백엔드가 동작할 포트
  port: 8060
##  cors허용해줄 fe코드
  feUri: https://i9a701.p.ssafy.io/testfe
  email: https://i9a701.p.ssafy.io/testfe
#  리다이렉트할때 쓸 변수
  # beUri: http://localhost:${varialbles.port}
  beUri: https://i9a701.p.ssafy.io/testbe

#여기서부터 설정파일
server:
  port: ${varialbles.port}

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jobterview?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:

        show_sql: true
  #        format_sql: true


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 682444755899-3eqgd34dqavn8mq0us3q4e0lf09pbc4v.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          kakao:
            client-id: f8ae067dc6798972969cd650aca79d01
            client-secret: u8FZ07hOCRzzLlr2QbVgHVnp5MeCSSuo
            redirect-uri: ${varialbles.beUri}/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

mail:
  smtp:
    timeout: 5000
    auth: true
    starttls:
      required: true
      enable: true
    socketFactory:
      class: javax.net.ssl.SSLSocketFactory
      fallback: false
      port: 465
    port: 465
    host: smtp.gmail.com

AdminMail:
  id: jobterview1@gmail.com
  password: sfktdjrnyxckwdka