spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jobterview?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    username: root
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
<<<<<<< HEAD
=======
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
>>>>>>> 4cfa8b4 (관리자, 메이트, 쪽지 완성)

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
<<<<<<< HEAD

         show_sql: true
#        format_sql: true
=======
#        show_sql: true
        format_sql: true

#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 682444755899-3eqgd34dqavn8mq0us3q4e0lf09pbc4v.apps.googleusercontent.com
#            client-secret: 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
#            scope:
#              - email
#              - profile

>>>>>>> 4cfa8b4 (관리자, 메이트, 쪽지 완성)

#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 682444755899-3eqgd34dqavn8mq0us3q4e0lf09pbc4v.apps.googleusercontent.com
#            client-secret: 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
#            scope:
#              - email
#              - profile


logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

